plugins {
    id 'idea'
    id 'java'
    id 'maven-publish'
    id 'com.diffplug.spotless' version '8.1.0'
    id 'com.azuredoom.hytale-tools' version '1.+'
    id 'com.azuredoom.hytalepublisher' version '1.+'
}

javadoc {
    options.addStringOption('Xdoclint:-missing', '-quiet')
}

configurations {
    testCompileOnly.extendsFrom compileOnly
    shade
}

group = project.group

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
}

hytaleTools {
    javaVersion = project.java_version as Integer
    hytaleVersion = project.hytale_version.toString()
    manifestServerVersion = project.manifestServerVersion.toString()
    manifestGroup = project.manifest_group.toString()
    modId = project.mod_id.toString()
    modDescription = project.mod_description.toString()
    modUrl = project.mod_url.toString()
    mainClass = project.main_class.toString()
    modCredits = project.mod_author.toString()
    manifestDependencies = project.manifest_dependencies.toString()
    manifestOptionalDependencies = project.manifest_opt_dependencies.toString()
    curseforgeId = project.curseforgeID.toString()
    disabledByDefault = project.disabled_by_default.toString().toBoolean()
    includesPack = project.includes_pack.toString().toBoolean()
    patchline = project.patchline.toString()

    debugEnabled = true
    debugPort = 5005
    debugSuspend = false

    hotSwapEnabled = true
    requireDcevm = true
    useHotswapAgent = true
    hotswapAgentPath = '/mnt/4C56E67556E65EE8/HyTale Mods/hotswap-agent-2.0.3.jar'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly "com.hypixel.hytale:Server:${hytale_version}"
    testRuntimeOnly 'com.azuredoom.hytalecustomassetloader:hytale-custom-asset-loader:1.1.3'
    implementation 'com.azuredoom.hytalecustomassetloader:hytale-custom-asset-loader:1.1.3'
    shade 'com.azuredoom.hytalecustomassetloader:hytale-custom-asset-loader:1.1.3'
    implementation 'curse.maven:dynamictooltipslib-1459711:7817318'
}

tasks.jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from {
        configurations.shade.collect { it.isDirectory() ? it : zipTree(it) }
    }

    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    systemProperty 'java.util.logging.manager', 'com.hypixel.hytale.logger.HytaleLogManager'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

spotless {
    java {
        eclipse().configFile("$rootDir/eclipse-formatter.xml")
        endWithNewline()
        importOrder("", "java", group.toString(), "\\#")
        leadingTabsToSpaces(4)
        removeUnusedImports()
        trimTrailingWhitespace()
    }
}

tasks.build {
    dependsOn("spotlessApply")
}

publishing {
    repositories {
        maven {
            name = "azuremaven"
            url = project.maven_url
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
    publications {
        maven(MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
            pom.withXml {
                asNode().dependencies.dependency.each { dep ->
                    if (dep.groupId.text() == 'curse.maven' || dep.groupId.text() == 'com.azuredoom.levelingcore' || dep.groupId.text() == 'com.buuz135') {
                        dep.parent().remove(dep)
                    }
                }
            }
        }
    }
}

hytalePublisher {
    version       = project.version
    releaseType   = "release"
    changelogFile = "changelog.md"
    gameVersion   = project.hytale_version.toString()

    modtale {
        enabled   = true
        projectId = project.modtale_uuid
        patchline = 'release'

        optional "2ebf130e-2189-4e90-9323-803a374d05ce", "1.5.2"
    }

    curseforge {
        enabled   = true
        projectId = project.curseforgeID

        optional "dynamictooltipslib"
    }

    modifold {
        enabled   = true
        projectId = project.mod_id
    }

    thunderstore {
        enabled    = true

        namespace  = project.mod_author
        websiteUrl = project.mod_url
        description = project.mod_description
        categories = ["plugins", "mods", "release"]
        hasNsfwContent = false
    }
}