plugins {
    id 'idea'
    id 'java'
    id 'maven-publish'
    id 'com.diffplug.spotless' version '8.1.0'
    id 'com.azuredoom.hytale-tools' version '1.0.+'
}

javadoc {
    options.addStringOption('Xdoclint:-missing', '-quiet')
}

configurations {
    testCompileOnly.extendsFrom compileOnly
    shade
}

group = project.group

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
}

hytaleTools {
    javaVersion = project.java_version as Integer
    hytaleVersion = project.hytale_version.toString()
    manifestGroup = project.manifest_group.toString()
    modId = project.mod_id.toString()
    modDescription = project.mod_description.toString()
    modUrl = project.mod_url.toString()
    mainClass = project.main_class.toString()
    modCredits = project.mod_author.toString()
    manifestDependencies = project.manifest_dependencies.toString()
    manifestOptionalDependencies = project.manifest_opt_dependencies.toString()
    curseforgeId = project.curseforgeID.toString()
    disabledByDefault = project.disabled_by_default.toString().toBoolean()
    includesPack = project.includes_pack.toString().toBoolean()
    patchline = project.patchline.toString()
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly "com.hypixel.hytale:Server:${hytale_version}"
    testRuntimeOnly 'com.azuredoom.hytalecustomassetloader:hytale-custom-asset-loader:1.1.2'
    implementation 'com.azuredoom.hytalecustomassetloader:hytale-custom-asset-loader:1.1.2'
    shade 'com.azuredoom.hytalecustomassetloader:hytale-custom-asset-loader:1.0.0'
    implementation 'curse.maven:dynamictooltipslib-1459711:7817318'
}

tasks.jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from {
        configurations.shade.collect { it.isDirectory() ? it : zipTree(it) }
    }

    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    systemProperty 'java.util.logging.manager', 'com.hypixel.hytale.logger.HytaleLogManager'
}

def serverRunDir = file("$projectDir/run")
if (!serverRunDir.exists()) {
    serverRunDir.mkdirs()
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

spotless {
    java {
        eclipse().configFile("$rootDir/eclipse-formatter.xml")
        endWithNewline()
        importOrder("", "java", group.toString(), "\\#")
        leadingTabsToSpaces(4)
        removeUnusedImports()
        trimTrailingWhitespace()
    }
}

tasks.build {
    dependsOn("spotlessApply")
}

publishing {
    repositories {
        maven {
            name = "azuremaven"
            url = project.maven_url
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
    publications {
        maven(MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
            pom.withXml {
                asNode().dependencies.dependency.each { dep ->
                    if (dep.groupId.text() == 'curse.maven' || dep.groupId.text() == 'com.azuredoom.levelingcore' || dep.groupId.text() == 'com.buuz135') {
                        dep.parent().remove(dep)
                    }
                }
            }
        }
    }
}

def keyPropsFile = new File(rootProject.projectDir, "key.properties")

if (keyPropsFile.exists()) {
    tasks.register("publishToModtale", Exec) {
        group = "publishing"
        description = "Publishes the built jar and changelog to Modtale.net."
        dependsOn tasks.named("build")
        def curlExe = org.gradle.internal.os.OperatingSystem.current().isWindows()
                ? "C:/Windows/System32/curl.exe"
                : "curl"

        doFirst {
            def releaseProp = new Properties()
            releaseProp.load(new FileInputStream(keyPropsFile))
            def apiKey = releaseProp.getProperty("modTaleKey")
            def projectId = releaseProp.getProperty("modTaleProjectId")
            def jarFile = layout.buildDirectory
                    .file("libs/${project.name}-${project.version}.jar")
                    .get().asFile
            def changelogFile = rootProject.file("changelog.md")
            def changelogText = changelogFile.text

            commandLine(
                    curlExe, '-X', 'POST',
                    "https://api.modtale.net/api/v1/projects/$projectId/versions",
                    '-H', "X-MODTALE-KEY: ${apiKey}",
                    '-F', "file=@${jarFile.absolutePath}",
                    '-F', "versionNumber=${project.version}",
                    '-F', "channel=${project.release_type}",
                    '-F', "gameVersions=${project.hytale_version}",
                    '-F', "changelog=${changelogText}",
                    '-F', "modIds[]=2ebf130e-2189-4e90-9323-803a374d05ce:1.5.2:optional"
            )
        }
    }
    // TODO: Move to hytale.curseforge.com when actually working because CurseForge didn't bother getting this ready dispute early access to Hytale.
    tasks.register("publishToCurseForge", Exec) {
        group = "publishing"
        description = "Publishes the built jar and changelog to CurseForge."
        dependsOn tasks.named("build")

        def curlExe = org.gradle.internal.os.OperatingSystem.current().isWindows()
                ? "C:/Windows/System32/curl.exe"
                : "curl"

        doFirst {
            def releaseProp = new Properties()
            releaseProp.load(new FileInputStream(keyPropsFile))
            def apiKey = releaseProp.getProperty("curseKey")

            def jarFile = layout.buildDirectory
                    .file("libs/${project.name}-${project.version}.jar")
                    .get().asFile

            def changelogText = rootProject.file("changelog.md").text
            def cfReleaseType = project.release_type.toString().toLowerCase()

            def requiredDeps = []

            def optionalDeps = []

            def dependencies = []

            requiredDeps.each {
                dependencies << [ slug: it, type: "requiredDependency" ]
            }
            optionalDeps.each {
                dependencies << [ slug: it, type: "optionalDependency" ]
            }

            def metadataObj = [
                    changelog     : changelogText,
                    changelogType : "markdown",
                    displayName   : "${project.name} ${project.version}",
                    gameVersions  : [14284],
                    releaseType   : cfReleaseType
            ]

            if (!dependencies.isEmpty()) {
                metadataObj.relations = [ projects: dependencies ]
            }

            def metadataJson = groovy.json.JsonOutput.toJson(metadataObj)

            commandLine(
                    curlExe,
                    "-sS",
                    "-X", "POST",
                    "https://legacy.curseforge.com/api/projects/${project.curseforgeID}/upload-file",
                    "-H", "X-Api-Token: ${apiKey}",
                    "-F", "metadata=${metadataJson};type=application/json",
                    "-F", "file=@${jarFile.absolutePath}"
            )
        }
    }
    tasks.register("publishToModifold", Exec) {
        group = "publishing"
        description = "Publishes the built jar and changelog to Modifold."
        dependsOn tasks.named("build")

        def curlExe = org.gradle.internal.os.OperatingSystem.current().isWindows()
                ? "C:/Windows/System32/curl.exe"
                : "curl"

        doFirst {
            def releaseProp = new Properties()
            releaseProp.load(new FileInputStream(keyPropsFile))

            def apiKey = releaseProp.getProperty("modifoldKey")
            def projectSlug = releaseProp.getProperty("modifoldProjectId")

            if (!apiKey) throw new GradleException("Missing modifoldKey in key.properties")
            if (!projectSlug) throw new GradleException("Missing modifoldProjectId in key.properties")

            def jarFile = layout.buildDirectory
                    .file("libs/${project.name}-${project.version}.jar")
                    .get().asFile

            def changelogText = rootProject.file("changelog.md").text

            commandLine(
                    curlExe,
                    "-sS",
                    "-X", "POST",
                    "https://api.modifold.com/projects/${projectSlug}/versions",
                    "-H", "Authorization: Bearer ${apiKey}",
                    "-F", "file=@${jarFile.absolutePath}",
                    "-F", "version_number=${project.version}",
                    "-F", "release_channel=${project.release_type.toString().toLowerCase()}",
                    "-F", 'game_versions=["Early Access"]',
                    "-F", 'loaders=["vanilla"]',
                    "-F", "changelog=${changelogText}"
            )
        }
    }
}