# Gradle
org.gradle.daemon = true
org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true
org.gradle.caching = true

# Common
java_version = 25
hytale_version = 0.+
manifestServerVersion = >=0.5.0 <0.6.0
release_type = RELEASE
maven_url = https://maven.azuredoom.com/mods

# Publishing
modtale_uuid = 97be62fd-fdb1-447d-9651-88dfe08723ec

# Mod options
group = com.azuredoom.tagcore
manifest_group = com.azuredoom
mod_name = TagCore
main_class = com.azuredoom.tagcore.TagCoreMod
mod_author = AzureDoom
mod_id = tagcore
mod_license = MIT
mod_description = A unified tagging API for items, blocks, and entities, enabling cross-mod compatibility
mod_url = https://example.com
version = 1.1.6
includes_pack = true
disabled_by_default = false
patchline = release
manifest_dependencies = Hytale:AssetModule=*
manifest_opt_dependencies = org.herolias:DynamicTooltipsLib=*
curseforgeID = 1522375
