# Gradle
org.gradle.daemon = true
org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true
org.gradle.caching = true

# Common
java_version = 25
hytale_version = 2026.04.17-c2d518cc9
release_type = RELEASE
maven_url = https://maven.azuredoom.com/mods

# Mod options
group = com.azuredoom.tagcore
manifest_group = com.azuredoom
mod_name = TagCore
main_class = com.azuredoom.tagcore.TagCoreMod
mod_author = AzureDoom
mod_id = tagcore
mod_license = MIT
mod_description = A unified tagging API for items, blocks, and entities, enabling cross-mod compatibility
mod_url = https://example.com
version = 1.0.0
includes_pack = true
disabled_by_default = false
patchline = pre-release
server_version = 2026.04.17-c2d518cc9
manifest_dependencies = Hytale:AssetModule=*
manifest_opt_dependencies = 
curseforgeID = 1522375
